export const UPDATE_SOUNDS = 'settings/UPDATE_SOUNDS';
export const UPDATE_RELEASE_CHANNEL = 'settings/UPDATE_RELEASE_CHANNEL';

export const UPDATE_CONCURRENT_DOWNLOADS =
  'settings/UPDATE_CONCURRENT_DOWNLOADS';

export const UPDATE_MINECRAFT_RESOLUTION =
  'settings/UPDATE_MINECRAFT_RESOLUTION';
export const UPDATE_JAVA_PATH = 'settings/UPDATE_JAVA_PATH';
export const UPDATE_JAVA_MEMORY = 'settings/UPDATE_JAVA_MEMORY';
export const UPDATE_JAVA_ARGUMENTS = 'settings/UPDATE_JAVA_ARGUMENTS';
export const UPDATE_DISCORD_RPC = 'settings/UPDATE_DISCORD_RPC';
export const HIDE_WINDOW_ON_GAME_LAUNCH = 'settings/HIDE_WINDOW_ON_GAME_LAUNCH';
export const UPDATE_POTATO_PC_MODE = 'settings/UPDATE_POTATO_PC_MODE';
export const UPDATE_SHOW_NEWS = 'settings/UPDATE_SHOW_NEWS';
export const UPDATE_CURSE_RELEASE_CHANNEL =
  'settings/UPDATE_CURSE_RELEASE_CHANNEL';
