sudo: true

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js:
        - node
        - 9
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: node_js
      node_js:
        - node
        - 9
      addons:
        apt:
          update: true
          sources:
            - sourceline: ppa:ubuntu-wine/ppa
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
            - xorriso
      deploy:
          provider: releases
          skip_cleanup: true
          api_key:
            secure: hF5RKP28CK3zGjqK++zNxMOjXNvGhq51kcbwV2hiMiBs8JSRVzLWgbemQ0qExVzvn5OxH+3GDlZLCeAfeZBjuC8cRqccWQyQ7OAT27PqW1ZvPCSsG6Xz53z6AC06A3j3DkcougqVSVbRBr6JLDZBlNxeVRle+KUM1f0CdmQJtBH71lYYiafmV/xu1rBG0zJJL60nhln84jiorKSekhVnLzyWH+W2H+a3Shl0/TcGvQAJ1oTCypYjmp7+/4vvRTX2wt016UVeW9UYPowBoJWvia3/5ptMJthoYdibQc0NrCvlx1E4L6HlNnrCSZwnxmP9d0mt5kekpmOu+QijS0OrwGSMADzwxfx34cwcLMoX/4Q/E4X4C6fgTSe8s3NODtfKtiiovgX6tNiTu+eLkV/UuRA3qxQGM9vlbbGv37CNY/VLSNbRsEQQsofTzKXjUZ09WcBrHrML2ZZ1j1TkPlkZBf8ZwyqF2Y4Zou+bRDuER1oAHzsptjap2GIa2F8mZ/im6p6DhlU0MvGo4LSbuJwdj5Gc0G/Yq296OUkvH7ue6LgzTceILygt7q2pwz2TJuEK8Sgs+/3wQ2wmjT3m3h4KMt0T1l/DPyZQbQDTUX/7jwI1ObvEbRLH5C+x5B163rN75MvWCDwPuBkErvRQTLE96h+GuGQZvxz34R84aB4zK0Y=
          file:
            - "release/GDLauncher-win.exe"
            - "release/GDLauncher-win.zip"
          on
            tags: true

cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules
    - $(npm config get prefix)/lib/node_modules
    - flow-typed
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/docker

install:
  - export CXX="g++-4.8"
  - yarn
  # On Linux, initialize "virtual display". See before_script
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      /sbin/start-stop-daemon \
      --start \
      --quiet \
      --pidfile /tmp/custom_xvfb_99.pid \
      --make-pidfile \
      --background \
      --exec /usr/bin/Xvfb \
      -- :99 -ac -screen 0 1280x1024x16
    else
      :
    fi

before_script:
  # On Linux, create a "virtual display". This allows browsers to work properly
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

script:
  - yarn package
#  - yarn lint
#  - yarn flow
#  - yarn test
#  - yarn test-e2e
  # On Linux, check if packaging to windows works
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn package --linux --win"
    else
      :
    fi

after_script:
- cd release
- ls

# deploy:
#   provider: releases
#   skip_cleanup: true
#   api_key:
#     secure: hF5RKP28CK3zGjqK++zNxMOjXNvGhq51kcbwV2hiMiBs8JSRVzLWgbemQ0qExVzvn5OxH+3GDlZLCeAfeZBjuC8cRqccWQyQ7OAT27PqW1ZvPCSsG6Xz53z6AC06A3j3DkcougqVSVbRBr6JLDZBlNxeVRle+KUM1f0CdmQJtBH71lYYiafmV/xu1rBG0zJJL60nhln84jiorKSekhVnLzyWH+W2H+a3Shl0/TcGvQAJ1oTCypYjmp7+/4vvRTX2wt016UVeW9UYPowBoJWvia3/5ptMJthoYdibQc0NrCvlx1E4L6HlNnrCSZwnxmP9d0mt5kekpmOu+QijS0OrwGSMADzwxfx34cwcLMoX/4Q/E4X4C6fgTSe8s3NODtfKtiiovgX6tNiTu+eLkV/UuRA3qxQGM9vlbbGv37CNY/VLSNbRsEQQsofTzKXjUZ09WcBrHrML2ZZ1j1TkPlkZBf8ZwyqF2Y4Zou+bRDuER1oAHzsptjap2GIa2F8mZ/im6p6DhlU0MvGo4LSbuJwdj5Gc0G/Yq296OUkvH7ue6LgzTceILygt7q2pwz2TJuEK8Sgs+/3wQ2wmjT3m3h4KMt0T1l/DPyZQbQDTUX/7jwI1ObvEbRLH5C+x5B163rN75MvWCDwPuBkErvRQTLE96h+GuGQZvxz34R84aB4zK0Y=
#   file: GDLauncher-1.0.0-mac.zip
#   on:
#     branch: release