//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twickt_Launcher.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twickt_Launcher.lang.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Assets.
        /// </summary>
        public static string analyzingAssets {
            get {
                return ResourceManager.GetString("analyzingAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Files.
        /// </summary>
        public static string analyzingFiles {
            get {
                return ResourceManager.GetString("analyzingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Forge Libraries.
        /// </summary>
        public static string analyzingForgeLibraries {
            get {
                return ResourceManager.GetString("analyzingForgeLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing JSON files.
        /// </summary>
        public static string analyzingJsonFiles {
            get {
                return ResourceManager.GetString("analyzingJsonFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Main Jar.
        /// </summary>
        public static string analyzingMainJar {
            get {
                return ResourceManager.GetString("analyzingMainJar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Mods.
        /// </summary>
        public static string analyzingMods {
            get {
                return ResourceManager.GetString("analyzingMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Standard Libraries.
        /// </summary>
        public static string analyzingStandardLibraries {
            get {
                return ResourceManager.GetString("analyzingStandardLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        public static string checkingForUpdates {
            get {
                return ResourceManager.GetString("checkingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Found(Compulsory Update).
        /// </summary>
        public static string compulsoryUpdateFound {
            get {
                return ResourceManager.GetString("compulsoryUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non e&apos; stato possibile scaricare la lista dei files della modpack.
        /// </summary>
        public static string couldNotGetModpackFiles {
            get {
                return ResourceManager.GetString("couldNotGetModpackFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non e&apos; stato possibile scaricare la lista delle modpacks.
        /// </summary>
        public static string couldNotGetModpacksList {
            get {
                return ResourceManager.GetString("couldNotGetModpacksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non e&apos; stato possibile verificare la versione.
        /// </summary>
        public static string couldNotVerifyVersion {
            get {
                return ResourceManager.GetString("couldNotVerifyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge Downloaded.
        /// </summary>
        public static string downloadedForge {
            get {
                return ResourceManager.GetString("downloadedForge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Forge.
        /// </summary>
        public static string downloadingForge {
            get {
                return ResourceManager.GetString("downloadingForge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading JAVA.
        /// </summary>
        public static string downloadingJava {
            get {
                return ResourceManager.GetString("downloadingJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&apos;e&apos; stato un errore scaricando le versioni. Il programma ora si chiudera&apos; per motivi di sicurezza.
        /// </summary>
        public static string errorDownloadingVersionsList {
            get {
                return ResourceManager.GetString("errorDownloadingVersionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nel ricevere i files della modpack.
        /// </summary>
        public static string errorGettingModpackFiles {
            get {
                return ResourceManager.GetString("errorGettingModpackFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in.
        /// </summary>
        public static string errorIn {
            get {
                return ResourceManager.GetString("errorIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il file estratto di forge non e&apos; stato trovato. Minecraft e&apos; probabile che non partira&apos;.
        /// </summary>
        public static string extractedForgeNotFound {
            get {
                return ResourceManager.GetString("extractedForgeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting JAVA.
        /// </summary>
        public static string extractingJava {
            get {
                return ResourceManager.GetString("extractingJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATAL ERROR.
        /// </summary>
        public static string fatalError {
            get {
                return ResourceManager.GetString("fatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non esiste il file installer di forge. Non e&apos; stato scaricato?.
        /// </summary>
        public static string forgeInstallerNotExist {
            get {
                return ResourceManager.GetString("forgeInstallerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error with JAVA Path (Process JAVA Recognition - ErrorDataReceived - JavaPath Empty).
        /// </summary>
        public static string javaPathError {
            get {
                return ResourceManager.GetString("javaPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON files analyzed.
        /// </summary>
        public static string jsonFileAnalyzed {
            get {
                return ResourceManager.GetString("jsonFileAnalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher attualmente in manutenzione, riprova piu&apos; tardi.
        /// </summary>
        public static string launcherMaintenance {
            get {
                return ResourceManager.GetString("launcherMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Modpacks.
        /// </summary>
        public static string loadingModpacks {
            get {
                return ResourceManager.GetString("loadingModpacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        public static string loggedInAs {
            get {
                return ResourceManager.GetString("loggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRORE NELLA VERIFICA MISTA DEI FILE..
        /// </summary>
        public static string mixFileCheckError {
            get {
                return ResourceManager.GetString("mixFileCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Updates Available.
        /// </summary>
        public static string noUpdatesAvailable {
            get {
                return ResourceManager.GetString("noUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a few moments we will open the new version.
        /// </summary>
        public static string openingNewVersion {
            get {
                return ResourceManager.GetString("openingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        public static string pleaseWait {
            get {
                return ResourceManager.GetString("pleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        public static string starting {
            get {
                return ResourceManager.GetString("starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Found.
        /// </summary>
        public static string updateFound {
            get {
                return ResourceManager.GetString("updateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string updating {
            get {
                return ResourceManager.GetString("updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the launcher.
        /// </summary>
        public static string updatingLauncher {
            get {
                return ResourceManager.GetString("updatingLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the launcher(Compulsory Update).
        /// </summary>
        public static string updatingLauncherCompulsory {
            get {
                return ResourceManager.GetString("updatingLauncherCompulsory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must update. Update?.
        /// </summary>
        public static string youMustUpdate {
            get {
                return ResourceManager.GetString("youMustUpdate", resourceCulture);
            }
        }
    }
}
