import path from 'path';
import getAppPath from './utils/getAppPath';

export const APPPATH = getAppPath.getAppPath();
export const LAUNCHER_FOLDER = 'launcherData';
export const INSTANCES_FOLDER = 'instances';
export const SERVERS_PATH = path.join(APPPATH, LAUNCHER_FOLDER, 'servers');
export const INSTANCES_PATH = path.join(APPPATH, LAUNCHER_FOLDER, INSTANCES_FOLDER);
export const PACKS_PATH = path.join(APPPATH, LAUNCHER_FOLDER, INSTANCES_FOLDER, 'packs');
export const GAME_VERSIONS_URL = 'https://launchermeta.mojang.com/mc/game/version_manifest.json';
export const ACCESS_TOKEN_VALIDATION_URL = 'https://authserver.mojang.com/validate';
export const ACCESS_TOKEN_REFRESH_URL = 'https://authserver.mojang.com/refresh';
export const LOGIN_PROXY_API = 'https://api.gdevs.io/auth';
export const LOGIN_TOKEN_PROXY_API = 'https://api.gdevs.io/authToken';
export const WINDOWS = 'win32';
export const LINUX = 'linux';
export const DARWIN = 'darwin';
export const NEWS_URL = 'https://minecraft.net/en-us/api/tiles/channel/not_set,Community%20content/region/None/category/Culture,Insider,News/page/1';
export const JAVA_URL = 'https://java.com/download';
export const UPDATE_URL = 'https://raw.githubusercontent.com/gorilla-devs/GDLauncher/master/package.json';
export const UPDATE_URL_CHECKSUMS = 'https://dl.gorilladevs.com/releases/latestChecksums.json';
