export const UPDATE_USERDATA = 'UPDATE_USERDATA';

export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const UPDATE_CURRENT_ACCOUNT_ID = 'UPDATE_CURRENT_ACCOUNT_ID';

export const UPDATE_LAST_UPDATE_VERSION = 'UPDATE_LAST_UPDATE_VERSION';

export const UPDATE_NEWS = 'UPDATE_NEWS';

export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';

export const ADD_DOWNLOAD_TO_QUEUE = 'ADD_DOWNLOAD_TO_QUEUE';
export const REMOVE_DOWNLOAD_FROM_QUEUE = 'REMOVE_DOWNLOAD_FROM_QUEUE';
export const UPDATE_TOTAL_FILES_TO_DOWNLOAD = 'UPDATE_TOTAL_FILES_TO_DOWNLOAD';
export const UPDATE_DOWNLOAD_PROGRESS = 'UPDATE_DOWNLOAD_PROGRESS';
export const UPDATE_DOWNLOAD_STATUS = 'UPDATE_DOWNLOAD_STATUS';

export const UPDATE_CURRENT_DOWNLOAD = 'UPDATE_CURRENT_DOWNLOAD';

export const UPDATE_INSTANCES = 'UPDATE_INSTANCES';
export const UPDATE_SPECIFIC_INSTANCE = 'UPDATE_SPECIFIC_INSTANCES';
export const REMOVE_SPECIFIC_INSTANCE = 'REMOVE_SPECIFIC_INSTANCE';
export const UPDATE_INSTANCES_STARTED = 'UPDATE_INSTANCES_STARTED';
export const ADD_STARTED_INSTANCE = 'ADD_STARTED_INSTANCE';
export const REMOVE_STARTED_INSTANCE = 'REMOVE_STARTED_INSTANCE';
export const UPDATE_STARTED_INSTANCE = 'UPDATE_STARTED_INSTANCE';
export const UPDATE_SELECTED_INSTANCE = 'UPDATE_SELECTED_INSTANCE';

export const ADD_SPECIFIC_INSTANCE_QUEUE = 'ADD_SPECIFIC_INSTANCE_QUEUE';
export const REMOVE_SPECIFIC_INSTANCE_QUEUE = 'REMOVE_SPECIFIC_INSTANCE_QUEUE';
export const UPDATE_INSTALLATION_STATUS = 'UPDATE_INSTALLATION_STATUS';
export const UPDATE_INSTALLATION_PROGRESS = 'UPDATE_INSTALLATION_PROGRESS';

export const UPDATE_MOD_MANIFESTS = 'UPDATE_MOD_MANIFESTS';
export const CLEAR_MOD_MANIFESTS = 'CLEAR_MOD_MANIFESTS';

export const UPDATE_VANILLA_MANIFEST = 'UPDATE_VANILLA_MANIFEST';
export const UPDATE_FORGE_MANIFEST = 'UPDATE_FORGE_MANIFEST';
export const UPDATE_CURSEFORGE_CATEGORIES_MANIFEST =
  'UPDATE_CURSEFORGE_CATEGORIES_MANIFEST';
export const UPDATE_FABRIC_MANIFEST = 'UPDATE_FABRIC_MANIFEST';
export const UPDATE_JAVA_MANIFEST = 'UPDATE_JAVA_MANIFEST';

export const UPDATE_CLIENT_TOKEN = 'UPDATE_CLIENT_TOKEN';
export const UPDATE_IS_NEW_USER = 'UPDATE_IS_NEW_USER';

export const UPDATE_UPDATE_AVAILABLE = 'UPDATE_UPDATE_AVAILABLE';
