export const INIT_STORE_VALUES = 'INIT_STORE_VALUES';

export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const UPDATE_CURRENT_ACCOUNT_ID = 'UPDATE_CURRENT_ACCOUNT_ID';

export const UPDATE_LAST_UPDATE_VERSION = 'UPDATE_LAST_UPDATE_VERSION';

export const UPDATE_NEWS = 'UPDATE_NEWS';
export const UPDATE_SHOW_NEWS = 'UPDATE_SHOW_NEWS';

export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';

export const UPDATE_INSTANCES = 'UPDATE_INSTANCES';
export const UPDATE_SPECIFIC_INSTANCE = 'UPDATE_SPECIFIC_INSTANCES';
export const REMOVE_SPECIFIC_INSTANCE = 'REMOVE_SPECIFIC_INSTANCE';
export const ADD_STARTING_INSTANCE = 'ADD_STARTING_INSTANCE';
export const ADD_STARTED_INSTANCE = 'ADD_STARTED_INSTANCE';
export const REMOVE_STARTED_INSTANCE = 'REMOVE_STARTED_INSTANCE';

export const ADD_SPECIFIC_INSTANCE_QUEUE = 'ADD_SPECIFIC_INSTANCE_QUEUE';
export const REMOVE_SPECIFIC_INSTANCE_QUEUE = 'REMOVE_SPECIFIC_INSTANCE_QUEUE';
export const UPDATE_INSTALLATION_STATUS = 'UPDATE_INSTALLATION_STATUS';
export const UPDATE_INSTALLATION_PROGRESS = 'UPDATE_INSTALLATION_PROGRESS';

export const UPDATE_IS_NEW_USER = 'UPDATE_IS_NEW_USER';

export const UPDATE_UPDATE_AVAILABLE = 'UPDATE_UPDATE_AVAILABLE';
