const ERRORS = {
  LOGIN: {
    EMPTY_USERNAME_OR_PASSWORD: 'EMPTY_USERNAME_OR_PASSWORD',
    WRONG_USERNAME_OR_PASSWORD: 'WRONG_USERNAME_OR_PASSWORD',
    DID_NOT_BUY_THE_GAME: 'DID_NOT_BUY_THE_GAME',
    ACCESS_TOKEN_MISSING: 'ACCESS_TOKEN_MISSING'
  }
};

export default ERRORS;
