const EV = {
  // DISCORD RPC
  INIT_DISCORD_RPC: 'INIT_DISCORD_RPC',
  UPDATE_DISCORD_RPC: 'UPDATE_DISCORD_RPC',
  SHUTDOWN_DISCORD_RPC: 'SHUTDOWN_DISCORD_RPC',

  // APP
  UPDATE_PROGRESS_BAR: 'UPDATE_PROGRESS_BAR',
  HIDE_MAIN_WINDOW: 'HIDE_MAIN_WINDOW',
  MINMAX_MAIN_WINDOW: 'MINMAX_MAIN_WINDOW',
  MINIMIZE_MAIN_WINDOW: 'MINIMIZE_MAIN_WINDOW',
  SHOW_MAIN_WINDOW: 'SHOW_MAIN_WINDOW',
  QUIT_APP: 'QUIT_APP',
  IS_APP_IMAGE: 'IS_APP_IMAGE',
  GET_APP_DATA_PATH: 'GET_APP_DATA_PATH',
  GET_APP_PATH: 'GET_APP_PATH',
  GET_USER_DATA_PATH: 'GET_USER_DATA_PATH',
  GET_EXECUTABLE_PATH: 'GET_EXECUTABLE_PATH',
  GET_APP_VERSION: 'GET_APP_VERSION',
  IS_MAIN_WINDOW_MAXIMIZED: 'IS_MAIN_WINDOW_MAXIMIZED',
  OPEN_FOLDER: 'OPEN_FOLDER',
  OPEN_FOLDER_DIALOG: 'OPEN_FOLDER_DIALOG',
  OPEN_FILE_DIALOG: 'OPEN_FILE_DIALOG',
  RESTART_APP: 'RESTART_APP',
  GET_ALL_DISPLAYS_BOUNDS: 'GET_ALL_DISPLAYS_BOUNDS',
  OPEN_MAIN_WINDOW_DEVTOOLS: 'OPEN_MAIN_WINDOW_DEVTOOLS',
  COPY_TEXT_TO_CLIPBOARD: 'COPY_TEXT_TO_CLIPBOARD',
  COPY_IMAGE_TO_CLIPBOARD: 'COPY_IMAGE_TO_CLIPBOARD',
  MAIN_WINDOW_MAXIMIZED: 'MAIN_WINDOW_MAXIMIZED',
  MAIN_WINDOW_MINIMIZED: 'MAIN_WINDOW_MINIMIZED',
  GET_7Z_PATH: 'GET_7Z_PATH',
  MAP_LIBRARIES: 'MAP_LIBRARIES',
  GET_FILE_HASH: 'GET_FILE_HASH',
  GET_FILES_RECURSIVE: 'GET_FILES_RECURSIVE',

  // JAVA
  INSTALL_JAVA: 'INSTALL_JAVA',
  UPDATE_JAVA_DOWNLOAD_PROGRESS: 'UPDATE_JAVA_DOWNLOAD_PROGRESS',
  UPDATE_JAVA_DOWNLOAD_STEP: 'UPDATE_JAVA_DOWNLOAD_STEP',

  // AUTO UPDATER
  UPDATE_AVAILABLE: 'UPDATE_AVAILABLE',
  CHECK_FOR_UPDATES: 'CHECK_FOR_UPDATES',
  APPLY_UPDATE: 'APPLY_UPDATE',

  // INSTANCES
  GET_INSTANCES: 'GET_INSTANCES',
  UPDATE_MOD_SYNC_STATE: 'UPDATE_MOD_SYNC_STATE',
  UPDATE_INSTANCES: 'UPDATE_INSTANCES',
  UPDATE_INSTANCES_QUEUE: 'UPDATE_INSTANCES_QUEUE',
  UPDATE_SPECIFIC_INSTANCE: 'UPDATE_SPECIFIC_INSTANCE',
  REMOVE_SPECIFIC_INSTANCE: 'REMOVE_SPECIFIC_INSTANCE',
  UPDATE_MANAGE_MODAL_INSTANCE_RENAME: 'UPDATE_MANAGE_MODAL_INSTANCE_RENAME',
  ADD_SPECIFIC_INSTANCE_QUEUE: 'ADD_SPECIFIC_INSTANCE_QUEUE',
  UPDATE_SPECIFIC_INSTANCE_QUEUE: 'UPDATE_SPECIFIC_INSTANCE_QUEUE',
  REMOVE_SPECIFIC_INSTANCE_QUEUE: 'REMOVE_SPECIFIC_INSTANCE_QUEUE',

  // INSTANCES ACTIONS
  TOGGLE_MOD_DISABLED: 'TOGGLE_MOD_DISABLED',
  DELETE_MODS: 'DELETE_MODS',
  INSTALL_MOD: 'INSTALL_MOD',
  UPDATE_MOD: 'UPDATE_MOD',
  RENAME_INSTANCE: 'RENAME_INSTANCE',

  // INSTANCES INSTALLATION
  ADD_INSTALLING_INSTANCE: 'ADD_INSTALLING_INSTANCE',
  UPDATE_INSTALLATION_STATUS: 'UPDATE_INSTALLATION_STATUS',
  UPDATE_INSTALLATION_PROGRESS: 'UPDATE_INSTALLATION_PROGRESS',
  INSTALL_INSTANCE: 'INSTALL_INSTANCE',
  APPLY_INSTALL_INSTANCE: 'APPLY_INSTALL_INSTANCE',
  UPDATE_MODPACK_VERSION: 'UPDATE_MODPACK_VERSION',
  CREATE_EXTRACT_ZIP: 'CREATE_EXTRACT_ZIP',

  // MANIFESTS
  UPDATE_MANIFESTS_FROM_DISK: 'UPDATE_MANIFESTS_FROM_DISK',
  UPDATE_MANIFESTS_FROM_APIS: 'UPDATE_MANIFESTS_FROM_APIS'
};

export default EV;
