const EV = {
  // DISCORD RPC
  INIT_DISCORD_RPC: 'INIT_DISCORD_RPC',
  UPDATE_DISCORD_RPC: 'UPDATE_DISCORD_RPC',
  SHUTDOWN_DISCORD_RPC: 'SHUTDOWN_DISCORD_RPC',

  // APP
  UPDATE_PROGRESS_BAR: 'UPDATE_PROGRESS_BAR',
  HIDE_MAIN_WINDOW: 'HIDE_MAIN_WINDOW',
  MINMAX_MAIN_WINDOW: 'MINMAX_MAIN_WINDOW',
  MINIMIZE_MAIN_WINDOW: 'MINIMIZE_MAIN_WINDOW',
  SHOW_MAIN_WINDOW: 'SHOW_MAIN_WINDOW',
  QUIT_APP: 'QUIT_APP',
  IS_APP_IMAGE: 'IS_APP_IMAGE',
  GET_APP_DATA_PATH: 'GET_APP_DATA_PATH',
  GET_APP_PATH: 'GET_APP_PATH',
  GET_USER_DATA_PATH: 'GET_USER_DATA_PATH',
  GET_EXECUTABLE_PATH: 'GET_EXECUTABLE_PATH',
  GET_APP_VERSION: 'GET_APP_VERSION',
  IS_MAIN_WINDOW_MAXIMIZED: 'IS_MAIN_WINDOW_MAXIMIZED',
  OPEN_FOLDER: 'OPEN_FOLDER',
  OPEN_FOLDER_DIALOG: 'OPEN_FOLDER_DIALOG',
  OPEN_FILE_DIALOG: 'OPEN_FILE_DIALOG',
  RESTART_APP: 'RESTART_APP',
  GET_ALL_DISPLAYS_BOUNDS: 'GET_ALL_DISPLAYS_BOUNDS',
  OPEN_MAIN_WINDOW_DEVTOOLS: 'OPEN_MAIN_WINDOW_DEVTOOLS',
  COPY_TEXT_TO_CLIPBOARD: 'COPY_TEXT_TO_CLIPBOARD',
  COPY_IMAGE_TO_CLIPBOARD: 'COPY_IMAGE_TO_CLIPBOARD',

  UPDATE_MOD_SYNC: 'UPDATE_MOD_SYNC',
  UPDATE_MOD_SYNC_LONG: 'UPDATE_MOD_SYNC_LONG'
};

export default EV;
