const EV = {
  // DISCORD RPC
  INIT_DISCORD_RPC: 'INIT_DISCORD_RPC',
  UPDATE_DISCORD_RPC: 'UPDATE_DISCORD_RPC',
  SHUTDOWN_DISCORD_RPC: 'SHUTDOWN_DISCORD_RPC',

  // APP
  UPDATE_PROGRESS_BAR: 'UPDATE_PROGRESS_BAR',
  HIDE_MAIN_WINDOW: 'HIDE_MAIN_WINDOW',
  MINMAX_MAIN_WINDOW: 'MINMAX_MAIN_WINDOW',
  MINIMIZE_MAIN_WINDOW: 'MINIMIZE_MAIN_WINDOW',
  SHOW_MAIN_WINDOW: 'SHOW_MAIN_WINDOW',
  QUIT_APP: 'QUIT_APP',
  IS_APP_IMAGE: 'IS_APP_IMAGE',
  GET_APP_VERSION: 'GET_APP_VERSION',
  IS_MAIN_WINDOW_MAXIMIZED: 'IS_MAIN_WINDOW_MAXIMIZED',
  OPEN_EXTERNAL: 'OPEN_EXTERNAL',
  OPEN_FOLDER_DIALOG: 'OPEN_FOLDER_DIALOG',
  OPEN_FILE_DIALOG: 'OPEN_FILE_DIALOG',
  RESTART_APP: 'RESTART_APP',
  GET_ALL_DISPLAYS_BOUNDS: 'GET_ALL_DISPLAYS_BOUNDS',
  OPEN_MAIN_WINDOW_DEVTOOLS: 'OPEN_MAIN_WINDOW_DEVTOOLS',
  COPY_TEXT_TO_CLIPBOARD: 'COPY_TEXT_TO_CLIPBOARD',
  COPY_IMAGE_TO_CLIPBOARD: 'COPY_IMAGE_TO_CLIPBOARD',
  MAIN_WINDOW_MAXIMIZED: 'MAIN_WINDOW_MAXIMIZED',
  MAIN_WINDOW_MINIMIZED: 'MAIN_WINDOW_MINIMIZED',
  MAP_LIBRARIES: 'MAP_LIBRARIES',
  GET_LAST_CHANGELOG_SHOWN: 'GET_LAST_CHANGELOG_SHOWN',
  SET_LAST_CHANGELOG_SHOWN: 'SET_LAST_CHANGELOG_SHOWN',
  GET_PLAYER_FACE_SKIN: 'GET_PLAYER_FACE_SKIN',

  GET_MANIFESTS: 'GET_MANIFESTS',

  // JAVA
  INSTALL_JAVA: 'INSTALL_JAVA',
  UPDATE_JAVA_DOWNLOAD_PROGRESS: 'UPDATE_JAVA_DOWNLOAD_PROGRESS',
  UPDATE_JAVA_DOWNLOAD_STEP: 'UPDATE_JAVA_DOWNLOAD_STEP',

  // AUTO UPDATER
  UPDATE_AVAILABLE: 'UPDATE_AVAILABLE',
  CHECK_FOR_UPDATES: 'CHECK_FOR_UPDATES',
  APPLY_UPDATE: 'APPLY_UPDATE',

  // INSTANCES
  GET_INSTANCES: 'GET_INSTANCES',
  UPDATE_MOD_SYNC_STATE: 'UPDATE_MOD_SYNC_STATE',
  UPDATE_INSTANCES: 'UPDATE_INSTANCES',
  UPDATE_INSTANCES_QUEUE: 'UPDATE_INSTANCES_QUEUE',
  UPDATE_SPECIFIC_INSTANCE: 'UPDATE_SPECIFIC_INSTANCE',
  REMOVE_SPECIFIC_INSTANCE: 'REMOVE_SPECIFIC_INSTANCE',
  UPDATE_MANAGE_MODAL_INSTANCE_RENAME: 'UPDATE_MANAGE_MODAL_INSTANCE_RENAME',
  ADD_SPECIFIC_INSTANCE_QUEUE: 'ADD_SPECIFIC_INSTANCE_QUEUE',
  UPDATE_SPECIFIC_INSTANCE_QUEUE: 'UPDATE_SPECIFIC_INSTANCE_QUEUE',
  REMOVE_SPECIFIC_INSTANCE_QUEUE: 'REMOVE_SPECIFIC_INSTANCE_QUEUE',
  GET_INSTANCE_BACKGROUND: 'GET_INSTANCE_BACKGROUND',
  GET_ALL_MC_VERSIONS: 'GET_ALL_MC_VERSIONS',

  // INSTANCES ACTIONS
  TOGGLE_MOD_DISABLED: 'TOGGLE_MOD_DISABLED',
  DELETE_MODS: 'DELETE_MODS',
  INSTALL_MOD: 'INSTALL_MOD',
  UPDATE_MOD: 'UPDATE_MOD',
  RENAME_INSTANCE: 'RENAME_INSTANCE',

  // INSTANCES INSTALLATION
  ADD_INSTALLING_INSTANCE: 'ADD_INSTALLING_INSTANCE',
  UPDATE_INSTALLATION_STATUS: 'UPDATE_INSTALLATION_STATUS',
  UPDATE_INSTALLATION_PROGRESS: 'UPDATE_INSTALLATION_PROGRESS',
  INSTALL_INSTANCE: 'INSTALL_INSTANCE',
  APPLY_INSTALL_INSTANCE: 'APPLY_INSTALL_INSTANCE',
  UPDATE_MODPACK_VERSION: 'UPDATE_MODPACK_VERSION',
  CREATE_EXTRACT_ZIP: 'CREATE_EXTRACT_ZIP',
  AUTH: {
    GET_PLAYER_SKIN_URL: 'auth/GET_PLAYER_SKIN_URL',
    GET_CLIENT_TOKEN: 'auth/GET_CLIENT_TOKEN',
    GET_MC_VANILLA_LAUNCHER_PROFILES_FROM_FILE:
      'auth/GET_MC_VANILLA_LAUNCHER_PROFILES_FROM_FILE',
    SET_MC_VANILLA_LAUNCHER_PROFILES_FROM_FILE:
      'auth/SET_MC_VANILLA_LAUNCHER_PROFILES_FROM_FILE'
  },
  PERSISTOR: {
    SET_CONCURRENT_DOWNLOADS: 'persistor/SET_CONCURRENT_DOWNLOADS',
    GET_CONCURRENT_DOWNLOADS: 'persistor/GET_CONCURRENT_DOWNLOADS',

    SET_SHOW_NEWS: 'persistor/SET_SHOW_NEWS',
    GET_SHOW_NEWS: 'persistor/GET_SHOW_NEWS',

    SET_IS_NEW_USER: 'persistor/SET_IS_NEW_USER',
    GET_IS_NEW_USER: 'persistor/GET_IS_NEW_USER',

    SET_CURRENT_ACCOUNT_ID: 'persistor/SET_CURRENT_ACCOUNT_ID',
    GET_CURRENT_ACCOUNT_ID: 'persistor/GET_CURRENT_ACCOUNT_ID',

    SET_ACCOUNTS: 'persistor/SET_ACCOUNTS',
    GET_ACCOUNTS: 'persistor/GET_ACCOUNTS',

    SET_POTATO_PC_MODE: 'persistor/SET_POTATO_PC_MODE',
    GET_POTATO_PC_MODE: 'persistor/GET_POTATO_PC_MODE'
  }
};

export default EV;
